### PR TITLE
App info API change

### PR DESCRIPTION
**Pull request by abdulhaseeb4239**
Added the change for the app info API change that returns the fee thresholds. 
API change: https://github.com/secretkeylabs/xverse-api/pull/163

### CODE REVIEW

**Review by m-aboelenein — APPROVED** [review]

**Comment by m-aboelenein** [comment]
published version is 0.23.2-beta-2

**Comment by DuskaT021** [comment]
I would need some context for testing @abdulhaseeb4239 thank you

**Comment by abdulhaseeb4239** [comment]
> I would need some context for testing @abdulhaseeb4239 thank you

This PR changed the appInfo function to get the BTC fee thresholds from the API.
you will need to install this version in order to test BTC fee threshold PR
https://github.com/secretkeylabs/xverse/pull/1089

**Comment by DuskaT021** [comment]
@m-aboelenein this is tested and it can be merged

**Pull request merged**
